### ISSUE TITLE
Unable to see weather charts.

### ISSUE THREAD

**Issue by haani104** [iashupal/TokopediaAssignment#1]
Steps to Reproduce

- Enter city name and press submit.
- City Map and Weather chart is displayed.
- Enter another city name and press submit.
- The city map is displayed but weather map is not displayed.

![screen shot 2018-01-02 at 7 39 23 am](https://user-images.githubusercontent.com/6011865/34472826-64db4994-ef90-11e7-9dae-6003e5ac189e.png)

**Comment by iashupal** [comment]
I resolve the issue of whether chart.
![snapshot](https://user-images.githubusercontent.com/26263771/35029110-4c47aed6-fb7f-11e7-978b-83be04ace0e4.PNG)
