### ISSUE TITLE
Mic icon displayed over Column Name

### ISSUE THREAD

**Issue by haani104** [iashupal/TokopediaAssignment#2]
A mic icon is displayed on column name.

![screen shot 2018-01-02 at 7 43 49 am](https://user-images.githubusercontent.com/6011865/34472875-119aed10-ef91-11e7-8b52-67e3b6f85315.png)

**Comment by iashupal** [comment]
A mic icon is display on its exact place.
![snapshot](https://user-images.githubusercontent.com/26263771/35029245-077cdaaa-fb80-11e7-9295-0f88e34293e5.PNG)
