### ISSUE TITLE
Able to enter empty string in input search box

### ISSUE THREAD

**Issue by haani104** [iashupal/TokopediaAssignment#3]
1. The input box accepts empty string, takes special characters
2. Upon submit, it send the same string to the API resulting in API failure.
3. No proper message is shown when the API returns, `{"cod":"404","message":"city not found"}`

![screen shot 2018-01-02 at 7 53 37 am](https://user-images.githubusercontent.com/6011865/34472936-1799465c-ef92-11e7-9d23-258c1d02a6dc.png)

Expected Behaviour
1. User should not be allowed to enter garbage data.
2. Submit button should call the api when valid text has been entered.
3. Upon failure of the API, the `message` should be shown to the user, i.e. coming from the API.

**Comment by iashupal** [comment]
![snapshot](https://user-images.githubusercontent.com/26263771/35034703-0fe2181c-fb95-11e7-81de-f1f508d201b5.PNG)
The input text box accept only character values
![snapshot](https://user-images.githubusercontent.com/26263771/35034661-f4ddbbe8-fb94-11e7-9960-679f845946ab.PNG)
