### ISSUE TITLE
Weather Chart not getting shown fully

### ISSUE THREAD

**Issue by haani104** [iashupal/TokopediaAssignment#4]
1. User has to scroll horizontally in order to see the chart

Expected Behaviour
1. Chart should be displayed within the width/height of the device. No Horizontal scroll should be there.

![screen shot 2018-01-02 at 7 56 22 am](https://user-images.githubusercontent.com/6011865/34472974-a7c6c920-ef92-11e7-96bb-93dad5d69453.png)
![screen shot 2018-01-02 at 7 56 29 am](https://user-images.githubusercontent.com/6011865/34472975-a7eeee5a-ef92-11e7-9be2-1216f75a01bf.png)

**Comment by iashupal** [comment]
Resolve whether chart issue. It shows in its exact position with full width.

![snapshot](https://user-images.githubusercontent.com/26263771/35029399-ca93c454-fb80-11e7-9098-424160fd7b22.PNG)
