### ISSUE TITLE
Map not utilizing full width of the column

### ISSUE THREAD

**Issue by haani104** [iashupal/TokopediaAssignment#5]
![screen shot 2018-01-02 at 7 56 22 am](https://user-images.githubusercontent.com/6011865/34473080-28121aca-ef94-11e7-9977-cd8e46572791.png)

**Comment by iashupal** [comment]
Resolve map width issue
![snapshot](https://user-images.githubusercontent.com/26263771/35029476-153da0ce-fb81-11e7-9d2f-a8f14d6f0669.PNG)
