### ISSUE TITLE
Map and Chart height not same

### ISSUE THREAD

**Issue by haani104** [iashupal/TokopediaAssignment#6]
![screen shot 2018-01-02 at 8 09 33 am](https://user-images.githubusercontent.com/6011865/34473092-55ed7746-ef94-11e7-8bbb-212b18463b5a.png)

**Comment by iashupal** [comment]
Map and chart have same height
![snapshot](https://user-images.githubusercontent.com/26263771/35029514-47be5160-fb81-11e7-82c0-6cfb312c7eaf.PNG)
